### ISSUE TITLE
Did you get the extension to work?

### ISSUE THREAD

**Issue by pftnhr** [pmoralesgarcia/yellow-webmention#1]
Hi Pablo,

unfortunately I haven't found any other way to contact you, so I'm asking here.

I am very interested in your Webmention extension. If it works, can you please update the repo?

Many thanks in advance
Robert

**Comment by pmoralesgarcia** [comment]
I'm starting to develop again!

**Comment by pmoralesgarcia** [comment]
@pftnhr Here is a start!

**Comment by pftnhr** [comment]
Hi Pablo, many thanks for that! A few things aren't quite running smoothly yet. 

A tip about the icons: Write the CSS in `webmention.css` to avoid collisions with the [yellow-icon](https://github.com/annaesvensson/yellow-icon) extension. Perhaps you can also use it for your extension.

I was cheeky enough to create a pull request with a few adjustments. 😄

**Comment by pmoralesgarcia** [comment]
Hi Robert! 
Thank you so much for the pull request! Great call on combining the `icon.css` into `webmention.css`. Less is more! I love all the changes made! :D It's only up from here!

I'm excited for this plugin!
